AllCops:
  NewCops: enable
Lint/AssignmentInCondition:
  Enabled: false
Style/MethodCallWithoutArgsParentheses:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/CaseIndentation:
  IndentOneStep: true
Layout/SpaceBeforeBlockBraces:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/FileName:
  Exclude:
    - 'lib/net-proto.rb'
